name: Coverage

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tarpaulin:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Install stable toolchain
          uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            toolchain: stable
            override: true

        - name: Install Required Packages
          run: |
          apt-get update && apt-get -y upgrade
          apt-get install -y build-essential libssl-dev

        - name: Run cargo-tarpaulin
          uses: actions-rs/tarpaulin@v0.1
          with:
            version: '0.32.3'
            args: "--lib"

        - name: Upload to codecov.io
          uses: codecov/codecov-action@v5
          with:
            file: ./cobertura.xml

